FROM node:20.5.1

ARG PORT 
ARG ME_CONFIG_MONGODB_URL
WORKDIR /opt/app
ADD package.json yarn.lock ./
RUN rm -rf node_modules \
    && yarn cache clean --force
RUN yarn install
ADD . .
RUN yarn build

ENV PORT=${PORT} \
    ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME} \
    ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD} \
    ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
CMD ["yarn", "start:dev"]